eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8768/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
user:
  role: Admin
