eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${MY_HOST:localhost}:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${MY_HOST:localhost}
user:
  role: Admin
