eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.3:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
user:
  role: Admin
